### PR TITLE
should not cancel

### PR DESCRIPTION
**Pull request by JeeChoi**
unsubscribe should not cancel context.

### CODE REVIEW

**Comment by JeeChoi** [comment]
I was trying to use the same client to concurrently make another sub request. After calling unsubscribe, the context would cancel the client connection and ALL the other concurrent requests would get canceled prematurely. Not the end of the world since I've change the code so I have a new client whenever we make a request, but if we want to have multiple subs/requests per same client, it will be a problem. IE if we were to replace current smoke test with this client, it would not work properly if we unsubscribed.

**Comment by JeeChoi** [comment]
I don't think cancel needs to be called in the subscription Unsubscribe().. I feel like we need a client.Close() function that cancels the context to shutdown the loop.go cleanly?

**Comment by ryanschneider** [comment]
Ok, trying to reproduce this locally now to determine what's happening.

**Comment by ryanschneider** [comment]
> I don't think cancel needs to be called in the subscription Unsubscribe().. I feel like we need a client.Close() function that cancels the context to shutdown the loop.go cleanly?

The way to shutdown the loop is to cancel the context passed into `NewClient`; the context/cancelFunc inside subscription _should_ be a totally separate (but child) context created in response to the subscription request here: https://github.com/INFURA/go-ethlibs/blob/master/node/loop.go#L151

Now, I think I do see some potential issues with the current code:

- `subscription.ch` is never closed
- subscriptions aren't removed from `loopingTransport.subscriptions` until the loop is shut down

I just tried adding `close(s.ch)` to subscription.Unsubscribe, but then during testing hit a race condition caused by the subscription not being removed from the subscriptions map I mentioned, leading to an attempt to deliver on a closed channel.

So, this might actually be same the underlaying issue you ran into.  So, I think I agree with your finding but believe we need to not just remove the call to cancel but probably remove `subscription.ctx` and `subscription.cancel` altogether, so I'm looking at how best to do that now.

**Comment by ryanschneider** [comment]
Ok, I think I have a fix for the bigger underlaying issue, it actually turned out to be a much bigger PR than I thought so still testing it, but I'll ping you as a reviewer once I'm done.

**Comment by JeeChoi** [comment]
closing since fixed in https://github.com/INFURA/go-ethlibs/pull/13

**Pull request closed without merging**
